### ISSUE TITLE
Do not run releaser-pleaser on all pull requests

### ISSUE THREAD

**Issue by jooola** [apricote/releaser-pleaser#137]
Currently, releaser-pleaser run on all pull requests, while I don't believe it is needed: https://github.com/hetznercloud/hcloud-cloud-controller-manager/actions/runs/12827616545/job/35769953824?pr=846

https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/4c239b674ed07327531e18a96dfe52911ea932d8/.github/workflows/releaser-pleaser.yml#L6-L10

I'd be in favor of only running it on the relevant branches, the one managed by releaser-pleaser:

```yml
name: Releaser-pleaser

on:
  push:
    branches: [main]
  pull_request_target:
    types: [edited, labeled, unlabeled]
    branches: ["releaser-pleaser--**"]
```
